### ISSUE TITLE
[길주] debop4j-data-ogm의 hibernate-ogm 4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by d2vfactory** [debop/debop4j#1]
hibernate-ogm 4.0.0-SNAPSHOT을 사용하기 위해서는
https://github.com/hibernate/hibernate-ogm 이 필요합니다.

다운 버전에서는 아래와 같은 Class는 사용 불가능 합니다.
org.hibernate.ogm.grid.EntityKeyMetadata
import org.hibernate.ogm.massindex.batchindexing.Consumer

가능하면 debop4j-data-ogm에서 hibernate-ogm은 4.0.0-SNAPSHOT version을 사용하세요.

**Comment by debop** [comment]
oh! no!

hibernate-ogm 4.0.0-SNAPSHOT 임

2013년 4월 23일 오전 11:54, Gilju notifications@github.com님의 말:

> hibernate-ogm 3.0.0-SNAPSHOT을 사용하기 위해서는
> https://github.com/hibernate/hibernate-ogm 이 필요합니다.
> 
> 다운 버전에서는 아래와 같은 Class는 사용 불가능 합니다.
> org.hibernate.ogm.grid.EntityKeyMetadata
> import org.hibernate.ogm.massindex.batchindexing.Consumer
> 
> 가능하면 debop4j-data-ogm에서 hibernate-ogm은 3.0.0-SNAPSHOT version을 사용하세요.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/debop/debop4j/issues/1
> .

## 

감사합니다^^

# 

Name: 배성혁(Sunghyouk Bae)
**Tel : 02-3289-2402
Mobile : 010-8955-5081
Mail : debop@kthcorp.com,  sunghyouk.bae@gmail.com

# KTH 플랫폼솔루션팀

**Comment by d2vfactory** [comment]
OMG~  typing errors :_)

**Comment by archmagece** [comment]
여기서 4.0.0-SNAPSHOT 다운되는 것 같습니다.

``` xml
        <repository>
            <id>jboss-snapshots</id>
            <url>http://snapshots.jboss.org/maven2</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```
