### ISSUE TITLE
multi datasource

### ISSUE THREAD

**Issue by d2vfactory** [debop/debop4j#2]
로직상 2개의 서로 다른 database를 사용해야 할 경우 어떤식으로 접근을 해야하나요?

**Comment by debop** [comment]
sessionFactory를 두 개 만들면 됩니다. (data source 를 wrapping 한 거라 생각하면 됩니다)
그리고 각각 session을 열고 (connection을 열고) 한 session을 통해 읽고, 다른 session에 저장하면 됩니다.
