### ISSUE TITLE
[송길주] 0.9.3 tag에 있는 소스가 0.9.4로 되어있습니다.

### ISSUE THREAD

**Issue by d2vfactory** [debop/debop4j#4]
태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
또한 https://bitbucket.org/debop/lucene-korean  repository는 비공개로 되어있는지 아직 제가 접속할 수 없었습니다.
d2vfactory@gmail.com 으로 초대 부탁드립니다.^^

감사합니다.

**Comment by debop** [comment]
왜 난…. 버전을 못 맞추지… 흠…
분명 맞추고 올린건뎅….

흠…. 

그냥 0.9.4 로 하세요.

내일 vital 도 0.9.4 로 맞출께요.

배성혁
sunghyouk.bae@gmail.com
1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:

**Comment by d2vfactory** [comment]
내용 차이 없으면 바이탈쪽엔 제가 그냥 0.9.4로 적용하도록 하겠습니다

lucene-korean repository만 허용시켜주세요 ^^

나의 iPhone에서 보냄
1. 6. 12. 오후 8:24 Sunghyouk Bae notifications@github.com 작성:

왜 난.... 버전을 못 맞추지... 흠...
분명 맞추고 올린건뎅....

흠....

그냥 0.9.4 로 하세요.

내일 vital 도 0.9.4 로 맞출께요.

배성혁
sunghyouk.bae@gmail.com
1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:

> 태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
> 또한 https://bitbucket.org/debop/lucene-korean repository는 비공개로 되어있는지 아직 제가
> 접속할 수 없었습니다.
> d2vfactory@gmail.com 으로 초대 부탁드립니다.^^
> 
> 감사합니다.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19319651
.

**Comment by debop** [comment]
루씬 한글 관련해서 읽기 가능으로 했어요
2013. 6. 12. 오후 8:48에 "Gilju" notifications@github.com님이 작성:

**Comment by debop** [comment]
빈도수 높은 단어 찾기 메소드 구현했습니다.

getMaxFreqTerms() 사용하면 됩니다.

2013년 6월 12일 오후 8:54, 배성혁 sunghyouk.bae@gmail.com님의 말:

> 루씬 한글 관련해서 읽기 가능으로 했어요
> 2013. 6. 12. 오후 8:48에 "Gilju" notifications@github.com님이 작성:
> 
> 내용 차이 없으면 바이탈쪽엔 제가 그냥 0.9.4로 적용하도록 하겠습니다
> 
> > lucene-korean repository만 허용시켜주세요 ^^
> > 
> > 나의 iPhone에서 보냄
> > 1. 6. 12. 오후 8:24 Sunghyouk Bae notifications@github.com 작성:
> > 
> > 왜 난.... 버전을 못 맞추지... 흠...
> > 분명 맞추고 올린건뎅....
> > 
> > 흠....
> > 
> > 그냥 0.9.4 로 하세요.
> > 
> > 내일 vital 도 0.9.4 로 맞출께요.
> > 
> > 배성혁
> > sunghyouk.bae@gmail.com
> > 1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:
> > 
> > > 태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
> > > 또한 https://bitbucket.org/debop/lucene-korean repository는 비공개로 되어있는지 아직
> > > 제가
> > > 접속할 수 없었습니다.
> > > d2vfactory@gmail.com 으로 초대 부탁드립니다.^^
> > > 
> > > 감사합니다.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19319651
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19320624
> > .

## 

감사합니다^^

# 

Name: 배성혁(Sunghyouk Bae) 이사
**Tel :
Mobile : 010-8955-5081
Mail :  debop@hconnect.co.kr ,  sunghyouk.bae@gmail.com

# HealthConnect 미래헬스케어융합연구소

**Comment by d2vfactory** [comment]
안녕하세요 송길주 입니다.

getMaxFreqTerms() 메서드가 현재 bitbucket 상에서 아래와 같이 TODO 상태로 구현이 안되어있습니다.
혹시 커밋하지 못하시건지 확인부탁 드립니다.

 @Override
    public List<FreqTerm> getMaxFreqTerms(int rank) throws
AvroRemoteException {
        if (log.isTraceEnabled()) log.trace("최대 빈도수를 구합니다. rank=[{}]", rank
);

```
    List<FreqTerm> results = new ArrayList<FreqTerm>();

    try (IUnitOfWork unitOfWork = UnitOfWorks.start()) {
        //
        // TODO: 구현해야 합니다.
        //
        // HighFreqTerms.getHighFreqTerms();

        throw new NotImplementedException("구현 중");
    } catch (Exception e) {
        log.error("빈도수 높은 단어들을 조회하는데 실패했습니다.", e);
    }

    return results;
}
```

2013년 6월 16일 오후 2:14, Sunghyouk Bae notifications@github.com님의 말:

**Comment by debop** [comment]
아 미치겠다...
집에서 push를 안하고 commit 만 했나봐... 집에 가서 push 하고 멜 다시 보낼께요.

2013년 6월 18일 오후 1:58, Gilju notifications@github.com님의 말:

> 안녕하세요 송길주 입니다.
> 
> getMaxFreqTerms() 메서드가 현재 bitbucket 상에서 아래와 같이 TODO 상태로 구현이 안되어있습니다.
> 혹시 커밋하지 못하시건지 확인부탁 드립니다.
> 
> @Override
> public List<FreqTerm> getMaxFreqTerms(int rank) throws
> AvroRemoteException {
> if (log.isTraceEnabled()) log.trace("최대 빈도수를 구합니다. rank=[{}]", rank
> );
> 
> List<FreqTerm> results = new ArrayList<FreqTerm>();
> 
> try (IUnitOfWork unitOfWork = UnitOfWorks.start()) {
> //
> // TODO: 구현해야 합니다.
> //
> // HighFreqTerms.getHighFreqTerms();
> 
> throw new NotImplementedException("구현 중");
> } catch (Exception e) {
> log.error("빈도수 높은 단어들을 조회하는데 실패했습니다.", e);
> }
> 
> return results;
> }
> 
> 2013년 6월 16일 오후 2:14, Sunghyouk Bae notifications@github.com님의 말:
> 
> > 빈도수 높은 단어 찾기 메소드 구현했습니다.
> > 
> > getMaxFreqTerms() 사용하면 됩니다.
> > 
> > 2013년 6월 12일 오후 8:54, 배성혁 sunghyouk.bae@gmail.com님의 말:
> > 
> > > 루씬 한글 관련해서 읽기 가능으로 했어요
> > > 2013. 6. 12. 오후 8:48에 "Gilju" notifications@github.com님이 작성:
> > > 
> > > 내용 차이 없으면 바이탈쪽엔 제가 그냥 0.9.4로 적용하도록 하겠습니다
> > > 
> > > > lucene-korean repository만 허용시켜주세요 ^^
> > > > 
> > > > 나의 iPhone에서 보냄
> > > > 1. 6. 12. 오후 8:24 Sunghyouk Bae notifications@github.com 작성:
> > > > 
> > > > 왜 난.... 버전을 못 맞추지... 흠...
> > > > 분명 맞추고 올린건뎅....
> > > > 
> > > > 흠....
> > > > 
> > > > 그냥 0.9.4 로 하세요.
> > > > 
> > > > 내일 vital 도 0.9.4 로 맞출께요.
> > > > 
> > > > 배성혁
> > > > sunghyouk.bae@gmail.com
> > > > 1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:
> > > > 
> > > > > 태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
> > > > > 또한 https://bitbucket.org/debop/lucene-korean repository는 비공개로
> > > > > 되어있는지
> > > > > 아직
> > > > > 제가
> > > > > 접속할 수 없었습니다.
> > > > > d2vfactory@gmail.com 으로 초대 부탁드립니다.^^
> > > > > 
> > > > > 감사합니다.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on
> > > > GitHub<
> > > > https://github.com/debop/debop4j/issues/4#issuecomment-19319651>
> > > > 
> > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/debop/debop4j/issues/4#issuecomment-19320624>
> > > > .
> > 
> > ## 
> > 
> > 감사합니다^^
> > 
> > # 
> > 
> > Name: 배성혁(Sunghyouk Bae) 이사
> > **Tel :
> > Mobile : 010-8955-5081
> > Mail : debop@hconnect.co.kr , sunghyouk.bae@gmail.com
> > 
> > # HealthConnect 미래헬스케어융합연구소
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/debop/debop4j/issues/4#issuecomment-19508047>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19590974
> .

## 

감사합니다^^

# 

Name: 배성혁(Sunghyouk Bae) 이사
**Tel :
Mobile : 010-8955-5081
Mail :  debop@hconnect.co.kr ,  sunghyouk.bae@gmail.com

# HealthConnect 미래헬스케어융합연구소

**Comment by d2vfactory** [comment]
네 감사합니다!

나의 iPhone에서 보냄
1. 6. 18. 오후 3:02 Sunghyouk Bae notifications@github.com 작성:

아 미치겠다...
집에서 push를 안하고 commit 만 했나봐... 집에 가서 push 하고 멜 다시 보낼께요.

2013년 6월 18일 오후 1:58, Gilju notifications@github.com님의 말:

> 안녕하세요 송길주 입니다.
> 
> getMaxFreqTerms() 메서드가 현재 bitbucket 상에서 아래와 같이 TODO 상태로 구현이 안되어있습니다.
> 혹시 커밋하지 못하시건지 확인부탁 드립니다.
> 
> @Override
> public List<FreqTerm> getMaxFreqTerms(int rank) throws
> AvroRemoteException {
> if (log.isTraceEnabled()) log.trace("최대 빈도수를 구합니다. rank=[{}]", rank
> );
> 
> List<FreqTerm> results = new ArrayList<FreqTerm>();
> 
> try (IUnitOfWork unitOfWork = UnitOfWorks.start()) {
> //
> // TODO: 구현해야 합니다.
> //
> // HighFreqTerms.getHighFreqTerms();
> 
> throw new NotImplementedException("구현 중");
> } catch (Exception e) {
> log.error("빈도수 높은 단어들을 조회하는데 실패했습니다.", e);
> }
> 
> return results;
> }
> 
> 2013년 6월 16일 오후 2:14, Sunghyouk Bae notifications@github.com님의 말:
> 
> > 빈도수 높은 단어 찾기 메소드 구현했습니다.
> > 
> > getMaxFreqTerms() 사용하면 됩니다.
> > 
> > 2013년 6월 12일 오후 8:54, 배성혁 sunghyouk.bae@gmail.com님의 말:
> > 
> > > 루씬 한글 관련해서 읽기 가능으로 했어요
> > > 2013. 6. 12. 오후 8:48에 "Gilju" notifications@github.com님이 작성:
> > > 
> > > 내용 차이 없으면 바이탈쪽엔 제가 그냥 0.9.4로 적용하도록 하겠습니다
> > > 
> > > > lucene-korean repository만 허용시켜주세요 ^^
> > > > 
> > > > 나의 iPhone에서 보냄
> > > > 1. 6. 12. 오후 8:24 Sunghyouk Bae notifications@github.com 작성:
> > > > 
> > > > 왜 난.... 버전을 못 맞추지... 흠...
> > > > 분명 맞추고 올린건뎅....
> > > > 
> > > > 흠....
> > > > 
> > > > 그냥 0.9.4 로 하세요.
> > > > 
> > > > 내일 vital 도 0.9.4 로 맞출께요.
> > > > 
> > > > 배성혁
> > > > sunghyouk.bae@gmail.com
> > > > 1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:
> > > > 
> > > > > 태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
> > > > > 또한 https://bitbucket.org/debop/lucene-korean repository는 비공개로
> > > > > 되어있는지
> > > > > 아직
> > > > > 제가
> > > > > 접속할 수 없었습니다.
> > > > > d2vfactory@gmail.com 으로 초대 부탁드립니다.^^
> > > > > 
> > > > > 감사합니다.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on
> > > > GitHub<
> > > > https://github.com/debop/debop4j/issues/4#issuecomment-19319651>
> > > > 
> > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/debop/debop4j/issues/4#issuecomment-19320624>
> > > > .
> > 
> > ## 
> > 
> > 감사합니다^^
> > 
> > # 
> > 
> > Name: 배성혁(Sunghyouk Bae) 이사
> > **Tel :
> > Mobile : 010-8955-5081
> > Mail : debop@hconnect.co.kr , sunghyouk.bae@gmail.com
> > 
> > # HealthConnect 미래헬스케어융합연구소
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/debop/debop4j/issues/4#issuecomment-19508047>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/debop/debop4j/issues/4#issuecomment-19590974>
> .

## 

감사합니다^^

# 

Name: 배성혁(Sunghyouk Bae) 이사
**Tel :
Mobile : 010-8955-5081
Mail : debop@hconnect.co.kr , sunghyouk.bae@gmail.com

# HealthConnect 미래헬스케어융합연구소

## 

Reply to this email directly or view it on
GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19592497
.

**Comment by debop** [comment]
꼬였었네요... 쩝...

이번에 동의어 검색과 빈도수 높은 단어 찾기 모두 추가했습니다.

2013년 6월 18일 오후 3:03, Gilju notifications@github.com님의 말:

> 네 감사합니다!
> 
> 나의 iPhone에서 보냄
> 1. 6. 18. 오후 3:02 Sunghyouk Bae notifications@github.com 작성:
> 
> 아 미치겠다...
> 집에서 push를 안하고 commit 만 했나봐... 집에 가서 push 하고 멜 다시 보낼께요.
> 
> 2013년 6월 18일 오후 1:58, Gilju notifications@github.com님의 말:
> 
> > 안녕하세요 송길주 입니다.
> > 
> > getMaxFreqTerms() 메서드가 현재 bitbucket 상에서 아래와 같이 TODO 상태로 구현이 안되어있습니다.
> > 혹시 커밋하지 못하시건지 확인부탁 드립니다.
> > 
> > @Override
> > public List<FreqTerm> getMaxFreqTerms(int rank) throws
> > AvroRemoteException {
> > if (log.isTraceEnabled()) log.trace("최대 빈도수를 구합니다. rank=[{}]", rank
> > );
> > 
> > List<FreqTerm> results = new ArrayList<FreqTerm>();
> > 
> > try (IUnitOfWork unitOfWork = UnitOfWorks.start()) {
> > //
> > // TODO: 구현해야 합니다.
> > //
> > // HighFreqTerms.getHighFreqTerms();
> > 
> > throw new NotImplementedException("구현 중");
> > } catch (Exception e) {
> > log.error("빈도수 높은 단어들을 조회하는데 실패했습니다.", e);
> > }
> > 
> > return results;
> > }
> > 
> > 2013년 6월 16일 오후 2:14, Sunghyouk Bae notifications@github.com님의 말:
> > 
> > > 빈도수 높은 단어 찾기 메소드 구현했습니다.
> > > 
> > > getMaxFreqTerms() 사용하면 됩니다.
> > > 
> > > 2013년 6월 12일 오후 8:54, 배성혁 sunghyouk.bae@gmail.com님의 말:
> > > 
> > > > 루씬 한글 관련해서 읽기 가능으로 했어요
> > > > 2013. 6. 12. 오후 8:48에 "Gilju" notifications@github.com님이 작성:
> > > > 
> > > > 내용 차이 없으면 바이탈쪽엔 제가 그냥 0.9.4로 적용하도록 하겠습니다
> > > > 
> > > > > lucene-korean repository만 허용시켜주세요 ^^
> > > > > 
> > > > > 나의 iPhone에서 보냄
> > > > > 1. 6. 12. 오후 8:24 Sunghyouk Bae notifications@github.com 작성:
> > > > > 
> > > > > 왜 난.... 버전을 못 맞추지... 흠...
> > > > > 분명 맞추고 올린건뎅....
> > > > > 
> > > > > 흠....
> > > > > 
> > > > > 그냥 0.9.4 로 하세요.
> > > > > 
> > > > > 내일 vital 도 0.9.4 로 맞출께요.
> > > > > 
> > > > > 배성혁
> > > > > sunghyouk.bae@gmail.com
> > > > > 1. 6. 12., 오후 8:16, Gilju notifications@github.com 작성:
> > > > > 
> > > > > > 태그로 만들어주신 0.9.3을 받아보니 소스는 0.9.4 버전으로 되어있습니다.
> > > > > > 또한 https://bitbucket.org/debop/lucene-korean repository는 비공개로
> > > > > > 되어있는지
> > > > > > 아직
> > > > > > 제가
> > > > > > 접속할 수 없었습니다.
> > > > > > d2vfactory@gmail.com 으로 초대 부탁드립니다.^^
> > > > > > 
> > > > > > 감사합니다.
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on
> > > > > GitHub<
> > > > > https://github.com/debop/debop4j/issues/4#issuecomment-19319651>
> > > > > 
> > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/debop/debop4j/issues/4#issuecomment-19320624>
> > > > > .
> > > 
> > > ## 
> > > 
> > > 감사합니다^^
> > > 
> > > # 
> > > 
> > > Name: 배성혁(Sunghyouk Bae) 이사
> > > **Tel :
> > > Mobile : 010-8955-5081
> > > Mail : debop@hconnect.co.kr , sunghyouk.bae@gmail.com
> > > 
> > > # HealthConnect 미래헬스케어융합연구소
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/debop/debop4j/issues/4#issuecomment-19508047>
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/debop/debop4j/issues/4#issuecomment-19590974>
> > .
> 
> ## 
> 
> 감사합니다^^
> 
> # 
> 
> Name: 배성혁(Sunghyouk Bae) 이사
> **Tel :
> Mobile : 010-8955-5081
> Mail : debop@hconnect.co.kr , sunghyouk.bae@gmail.com
> 
> # HealthConnect 미래헬스케어융합연구소
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19592497
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/debop/debop4j/issues/4#issuecomment-19592554
> .

## 

감사합니다^^

# 

Name: 배성혁(Sunghyouk Bae) 이사
**Tel :
Mobile : 010-8955-5081
Mail :  debop@hconnect.co.kr ,  sunghyouk.bae@gmail.com

# HealthConnect 미래헬스케어융합연구소
